os:
  - linux
  - osx

# This makes us use Ubuntu 14 instead of 12
dist: trusty

language: c
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgtk-3-dev -y || sudo apt-cache search libgtk3; fi
  - make -f GNUmakefile
  - make -f GNUmakefile test
  - make -f GNUmakefile examples 
